"""fix

Revision ID: 0788fa77e537
Revises: a520954ed464
Create Date: 2026-02-27 16:37:43.388579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0788fa77e537'
down_revision: Union[str, Sequence[str], None] = 'a520954ed464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('homeworks_lesson_id_fkey'), 'homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'homeworks', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.create_foreign_key(op.f('homeworks_lesson_id_fkey'), 'homeworks', 'homeworks', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
