"""fix

Revision ID: 2fc4e9deb702
Revises: 3b3278589800
Create Date: 2026-02-26 14:08:58.947704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc4e9deb702'
down_revision: Union[str, Sequence[str], None] = '3b3278589800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('lessons', 'pdf_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('pdf_file_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_table('lesson_screenshots')
    # ### end Alembic commands ###
