"""fix

Revision ID: 349a70e24c83
Revises: 7630069e9d3c
Create Date: 2026-02-20 20:00:25.125446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349a70e24c83'
down_revision: Union[str, Sequence[str], None] = '7630069e9d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_student', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_student', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.drop_column('teacher_student', 'subject_id')
    # ### end Alembic commands ###
