"""fix

Revision ID: 49c5e19c6c8b
Revises: aab7ff5c6378
Create Date: 2026-03-03 15:27:13.013292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c5e19c6c8b'
down_revision: Union[str, Sequence[str], None] = 'aab7ff5c6378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lessons_done_homework_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'done_homework_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('done_homework_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lessons_done_homework_id_fkey'), 'lessons', 'done_homeworks', ['done_homework_id'], ['id'])
    # ### end Alembic commands ###
