"""fix

Revision ID: 4b16353ee677
Revises: 910e71cd24ee
Create Date: 2026-03-09 15:14:59.110851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b16353ee677'
down_revision: Union[str, Sequence[str], None] = '910e71cd24ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('done_homework_screenshots_done_homework_id_fkey'), 'done_homework_screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'done_homework_screenshots', 'done_homeworks', ['done_homework_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('done_homeworks_lesson_id_fkey'), 'done_homeworks', type_='foreignkey')
    op.drop_constraint(op.f('done_homeworks_student_id_fkey'), 'done_homeworks', type_='foreignkey')
    op.drop_constraint(op.f('done_homeworks_homework_id_fkey'), 'done_homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'done_homeworks', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'done_homeworks', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'done_homeworks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('homework_screenshots_homework_id_fkey'), 'homework_screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'homework_screenshots', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('homeworks_student_id_fkey'), 'homeworks', type_='foreignkey')
    op.drop_constraint(op.f('homeworks_teacher_id_fkey'), 'homeworks', type_='foreignkey')
    op.drop_constraint(op.f('homeworks_subject_id_fkey'), 'homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'homeworks', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'homeworks', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'homeworks', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lesson_screenshots_lesson_id_fkey'), 'lesson_screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_screenshots', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lessons_homework_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('lessons_subject_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('lessons_teacher_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('lessons_student_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lessons', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lessons', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lessons', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('schedules_student_id_fkey'), 'schedules', type_='foreignkey')
    op.drop_constraint(op.f('schedules_subject_id_fkey'), 'schedules', type_='foreignkey')
    op.drop_constraint(op.f('schedules_teacher_id_fkey'), 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedules', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedules', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key(op.f('schedules_teacher_id_fkey'), 'schedules', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('schedules_subject_id_fkey'), 'schedules', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('schedules_student_id_fkey'), 'schedules', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_student_id_fkey'), 'lessons', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('lessons_teacher_id_fkey'), 'lessons', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('lessons_subject_id_fkey'), 'lessons', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('lessons_homework_id_fkey'), 'lessons', 'homeworks', ['homework_id'], ['id'])
    op.drop_constraint(None, 'lesson_screenshots', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_screenshots_lesson_id_fkey'), 'lesson_screenshots', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.create_foreign_key(op.f('homeworks_subject_id_fkey'), 'homeworks', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('homeworks_teacher_id_fkey'), 'homeworks', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('homeworks_student_id_fkey'), 'homeworks', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'homework_screenshots', type_='foreignkey')
    op.create_foreign_key(op.f('homework_screenshots_homework_id_fkey'), 'homework_screenshots', 'homeworks', ['homework_id'], ['id'])
    op.drop_constraint(None, 'done_homeworks', type_='foreignkey')
    op.drop_constraint(None, 'done_homeworks', type_='foreignkey')
    op.drop_constraint(None, 'done_homeworks', type_='foreignkey')
    op.create_foreign_key(op.f('done_homeworks_homework_id_fkey'), 'done_homeworks', 'homeworks', ['homework_id'], ['id'])
    op.create_foreign_key(op.f('done_homeworks_student_id_fkey'), 'done_homeworks', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('done_homeworks_lesson_id_fkey'), 'done_homeworks', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'done_homework_screenshots', type_='foreignkey')
    op.create_foreign_key(op.f('done_homework_screenshots_done_homework_id_fkey'), 'done_homework_screenshots', 'done_homeworks', ['done_homework_id'], ['id'])
    # ### end Alembic commands ###
