"""fix

Revision ID: 67264e32a4ba
Revises: d02f912fc61d
Create Date: 2026-03-11 14:17:06.661615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67264e32a4ba'
down_revision: Union[str, Sequence[str], None] = 'd02f912fc61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done_homework_screenshots', 'mark')
    op.add_column('done_homeworks', sa.Column('mark', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done_homeworks', 'mark')
    op.add_column('done_homework_screenshots', sa.Column('mark', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
