"""fix

Revision ID: 690797f19ccd
Revises: 0788fa77e537
Create Date: 2026-02-27 16:40:01.867069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690797f19ccd'
down_revision: Union[str, Sequence[str], None] = '0788fa77e537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('homeworks_lesson_id_fkey'), 'homeworks', type_='foreignkey')
    op.drop_column('homeworks', 'lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('homeworks_lesson_id_fkey'), 'homeworks', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
