"""fix

Revision ID: 6a96e66da707
Revises: 4b16353ee677
Create Date: 2026-03-09 15:17:40.060310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a96e66da707'
down_revision: Union[str, Sequence[str], None] = '4b16353ee677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teacher_student_subject_id_fkey'), 'teacher_student', type_='foreignkey')
    op.drop_constraint(op.f('teacher_student_student_id_fkey'), 'teacher_student', type_='foreignkey')
    op.drop_constraint(op.f('teacher_student_teacher_id_fkey'), 'teacher_student', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_student', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_student', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_student', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_student_teacher_id_fkey'), 'teacher_student', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('teacher_student_student_id_fkey'), 'teacher_student', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('teacher_student_subject_id_fkey'), 'teacher_student', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
