"""fix

Revision ID: 80c382c48cf0
Revises: 2fc4e9deb702
Create Date: 2026-02-26 14:49:04.612755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c382c48cf0'
down_revision: Union[str, Sequence[str], None] = '2fc4e9deb702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('lessons', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'created_at')
    op.drop_column('lessons', 'is_active')
    # ### end Alembic commands ###
