"""fix

Revision ID: a520954ed464
Revises: e437c664fa14
Create Date: 2026-02-27 16:09:26.101041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a520954ed464'
down_revision: Union[str, Sequence[str], None] = 'e437c664fa14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'homeworks', 'homeworks', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.drop_column('homeworks', 'lesson_id')
    # ### end Alembic commands ###
