"""fix

Revision ID: aab7ff5c6378
Revises: 28f36f382ed3
Create Date: 2026-03-03 15:22:14.683432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab7ff5c6378'
down_revision: Union[str, Sequence[str], None] = '28f36f382ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('done_homework_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'done_homeworks', ['done_homework_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'done_homework_id')
    # ### end Alembic commands ###
