"""fix

Revision ID: b2725279e7f4
Revises: 349a70e24c83
Create Date: 2026-02-20 21:09:02.382654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2725279e7f4'
down_revision: Union[str, Sequence[str], None] = '349a70e24c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_teacher_student_subject', 'teacher_student', ['student_id', 'teacher_id', 'subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_teacher_student_subject', 'teacher_student', type_='unique')
    # ### end Alembic commands ###
