"""fix

Revision ID: b96651dc5124
Revises: 6a96e66da707
Create Date: 2026-03-09 15:23:54.747428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96651dc5124'
down_revision: Union[str, Sequence[str], None] = '6a96e66da707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('quantity_tasks', sa.Integer(), nullable=False))
    op.drop_column('lessons', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'quantity_tasks')
    # ### end Alembic commands ###
