"""fix

Revision ID: c29b37d205c8
Revises: 0f72a9cedb44
Create Date: 2026-03-03 14:31:50.381116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29b37d205c8'
down_revision: Union[str, Sequence[str], None] = '0f72a9cedb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done_homework_screenshots', sa.Column('done_homework_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('done_homework_screenshots_homework_id_fkey'), 'done_homework_screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'done_homework_screenshots', 'done_homeworks', ['done_homework_id'], ['id'])
    op.drop_column('done_homework_screenshots', 'homework_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done_homework_screenshots', sa.Column('homework_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'done_homework_screenshots', type_='foreignkey')
    op.create_foreign_key(op.f('done_homework_screenshots_homework_id_fkey'), 'done_homework_screenshots', 'homeworks', ['homework_id'], ['id'])
    op.drop_column('done_homework_screenshots', 'done_homework_id')
    # ### end Alembic commands ###
