"""fix

Revision ID: c7c70ef2db37
Revises: b2725279e7f4
Create Date: 2026-02-23 15:44:26.333065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c70ef2db37'
down_revision: Union[str, Sequence[str], None] = 'b2725279e7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='daysenum'), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_student_id'), 'schedules', ['student_id'], unique=False)
    op.create_index(op.f('ix_schedules_subject_id'), 'schedules', ['subject_id'], unique=False)
    op.create_index(op.f('ix_schedules_teacher_id'), 'schedules', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_teacher_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_subject_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_student_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
