"""fix

Revision ID: d02f912fc61d
Revises: b96651dc5124
Create Date: 2026-03-11 14:09:10.158504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02f912fc61d'
down_revision: Union[str, Sequence[str], None] = 'b96651dc5124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done_homework_screenshots', sa.Column('mark', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done_homework_screenshots', 'mark')
    # ### end Alembic commands ###
