"""fix

Revision ID: e437c664fa14
Revises: 80c382c48cf0
Create Date: 2026-02-26 17:23:39.931622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e437c664fa14'
down_revision: Union[str, Sequence[str], None] = '80c382c48cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('homeworks', 'pdf_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('pdf_file_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_table('homework_screenshots')
    # ### end Alembic commands ###
